let words = `people – pueblo 
time – el tiempo 
year – el año 
thing – la cosa 
way – el camino 
day – el día 
man – el hombre 
state – el estado 
lot – el lote
woman – la mujer
country – el país
life – la vida
question – la cuestión
president – el presidente
child – el niño
week – la semana
world – el mundo
kind – el tipo
case – el caso
problem – el problema
fact – el hecho
family – la familia
story – la historia
point – el punto
government – el gobierno
money – el dinero
issue – la cuestión
part – la parte
morning – la mañana
guy – el chico
number – el número
job – el trabajo
night – la noche
right – el derecho
school – la escuela
place – el lugar
war – la guerra
kid – el niño
month – el mes
book – el libro
hour – la hora
show – el show
police – la policía
program – el programa
party – el partido
law – la ley
word – la palabra
person – la persona
home – el hogar
business – el negocio
friend – el amigo
company – la empresa
side – el lado
tax – el impuesto
democrat – el demócrata
group – el grupo
moment – el momento
break – la ruptura
idea – la idea
member – el miembro
system – el sistema de
minute – el minuto
reason – la razón
campaign – la campaña
work – la obra
nation – la nación
congress – el congreso
mother – la madre
force – la fuerza
health – la salud
back – la parte de atrás
area – la zona
name – el nombre
report – el informe
hand – la mano
line – la línea
end – el fin
court – la corte
care – el cuidado
couple – la pareja
house – la casa
american – la americana
father – el padre
situation – la situación
car – el coche
parent – el padre
administration – la administración
drug – la droga
city – la ciudad
sense – el sentido
policy – la política
office – la oficina
decision – la decisión
power – el poder
plan – el plan
leader – el líder
information – la información
election – la elección
movie – la película
death – la muerte
air – el aire
call – la llamada
community – la comunidad
look – la mirada
evidence – la evidencia
girl – la chica
doctor – el médico
vote – el voto
video – el video
picture – la imagen
room – la habitación
economy – la economía
phone – el teléfono
history – la historia
sort – el tipo
boy – el niño
crime – el crimen
process – el proceso de
wife – la esposa
music – la música
water – el agua
service – el servicio
record – el registro
security – la seguridad
talk – la charla
mind – la mente
head – la cabeza
candidate – el candidato
official – el funcionario
camera – la cámara
student – el estudiante
attack – el ataque
chance – la oportunidad
game – el juego
baby – el bebé
south – el sur
change – cambio
trial – el juicio
body – el cuerpo
market – el mercado
stuff – las cosas
interest – el interés
weapon – el arma
heart – el corazón
son – el hijo
team – el equipo
town – la ciudad
television – la televisión
will – la voluntad
troop – la tropa
judge – el juez
action – la acción
answer – la respuesta
position – la posición
view – la vista
difference – la diferencia
food – la comida
daughter – la hija
race – la carrera
deal – el acuerdo
street – la calle
price – el precio
message – el mensaje
control – el control
debate – el debate
officer – el oficial
film – la película
level – el nivel
effort – el esfuerzo
relationship – la relación
correspondent – el corresponsal
ground – el terreno
piece – la pieza
husband – el marido
budget – el presupuesto
jury – el jurado
reporter – el reportero
weekend – el fin de semana
matter – la materia
age – la edad
gun – la pistola
peace – la paz
murder – el asesinato
role – el papel
investigation – la investigación
experience – la experiencia
hospital – el hospital
eye – el ojo
director – el director
future – el futuro
face – la cara
oil – el aceite
result – el resultado
public – el público
lawyer – el abogado
poll – la encuesta
second – la segunda
opportunity – la oportunidad
industry – la industria
brother – el hermano
statement – la declaración
fire – el fuego
love – el amor
rate – la tasa
effect – el efecto
song – la canción
event – el evento
charge – la carga
support – el apoyo
radio – la radio
building – el edificio
bank – el banco
victim – la víctima
door – la puerta
interview – la entrevista
scene – la escena
rest – el resto
press – la prensa
attention – la atención
choice – la elección
speech – el discurso
patient – el paciente
truth – la verdad
road – la carretera
term – el término
site – el sitio
worker – el trabajador
professor – el profesor
letter – la letra
reform – la reforma
concern – la preocupación
folk – la gente
sex – el sexo
study – el estudio
college – la universidad
voter – el votante
wall – la pared
evening – la noche
meeting – la reunión
voice – la voz
audience – la audiencia
violence – la violencia
rule – la regla
star – la estrella
test – la prueba
education – la educación
trouble – el problema
risk – el riesgo
prison – la prisión
guest – el invitado
class – la clase
society – la sociedad
soldier – el soldado
plane – el plano
amount – la cantidad
help – la ayuda
cost – el costo
authority – la autoridad
foot – el pie
period – el período
feeling – la sensación
step – la etapa de
cause – causa
tape – la cinta
threat – la amenaza
opinion – la opinión
organization – la organización
type – el tipo de
conversation – la conversación
disease – la enfermedad
operation – la operación
cancer – el cáncer
magazine – la revista
governor – el gobernador
pressure – la presión
majority – la mayoría
research – La investigación
character – el carácter
station – la estación
crisis – la crisis
expert – el experto
blood – la sangre
chairman – el presidente
argument – el argumento
list – la lista
dog – el perro
computer – el ordenador
beginning – el principio
insurance – el seguro
field – el campo
sister – la hermana
mistake – el error
player – el jugador
energy – la energía
paper – el documento
space – el espacio
store – la tienda
agreement – el acuerdo
responsibility – la responsabilidad
lady – la dama
order – el orden
summer – el verano
product – el producto
value – el valor
stock – la acción
intelligence – la inteligencia
teacher – el profesor
agency – la agencia
trade – el comercio
conference – la conferencia
cell – la célula
church – la iglesia
comment – el comentario
source – la fuente
past – el pasado
cut – el corte
thought – el pensamiento
credit – el crédito
hope – la esperanza
sign – el signo
career – la carrera
marriage – el matrimonio
condition – la condición
witness – el testigo
technology – la tecnología
stage – la etapa de
staff – el personal
arm – el brazo
mission – la misión
art – el arte
actor – el actor
battle – la batalla
top – la parte superior
citizen – el ciudadano
author – el autor
reaction – la reacción
gentleman – el caballero
leadership – el liderazgo
fear – el miedo
example – el ejemplo
language – el idioma
need – la necesidad
justice – la justicia
discussion – la discusión
border – la frontera
animal – el animal
detail – el detalle
response – la respuesta
network – la red
movement – el movimiento
use – el uso
male – el macho
capital – la capital
hearing – la audiencia
standard – la norma
benefit – el beneficio
table – la tabla
treatment – el tratamiento
agent – el agente
card – la tarjeta
shot – el disparo
board – el tablero
reality – la realidad
sir – el señor
land – la tierra
project – el proyecto
light – la luz
image – la imagen
century – el siglo
page – la página
success – el éxito
sound – el sonido
impact – el impacto
pain – el dolor
season – la temporada
individual – el individuo
sport – el deporte
studio – el estudio
decade – la década
challenge – el desafío
dream – el sueño
newspaper – el periódico
floor – el piso
fight – la lucha
safety – la seguridad
act – el acto
trip – el viaje
course – el curso
possibility – la posibilidad
freedom – la libertad
fund – el fondo
seat – el asiento
bomb – la bomba
form – la forma
executive – el ejecutivo
minister – el ministro
deficit – el déficit
development – el desarrollo
flight – el vuelo
secretary – el secretario
committee – el comité
consumer – el consumidor
rock – la roca
figure – la figura
subject – el sujeto
culture – la cultura
hair – el cabello
coverage – la cobertura
loss – la pérdida
dad – el papá
note – la nota
activity – la actividad
goal – el objetivo
option – la opción
gas – el gas
region – la región
population – la población
ability – la capacidad
resolution – la resolución
employee – el empleado
brain – el cerebro
politician – el político
middle – el centro
storm – la tormenta
generation – la generación
critic – el crítico
fan – el ventilador
scientist – el científico
target – el objetivo
camp – el campamento
afternoon – la tarde
direction – la dirección
science – la ciencia
journalist – el periodista
degree – el grado
affair – el asunto
damage – el daño
strategy – la estrategia
factor – el factor
plant – la planta
democracy – la democracia
doubt – la duda
solution – la solución
spending – el gasto
training – la formación
abuse – el abuso
danger – el peligro
environment – el medio ambiente
memory – la memoria
nature – la naturaleza
material – el material
document – el documento
income – los ingresos
analyst – el analista
play – el juego
guard – la guardia
hotel – el hotel
editor – el editor
missile – el misil
accident – el accidente
purpose – el propósito
writer – el escritor
emergency – la emergencia
growth – el crecimiento
bed – la cama
welfare – el bienestar
adult – el adulto
faith – la fe
proposal – la propuesta
model – el modelo
army – el ejército
incident – el incidente
box – la caja
crowd – la multitud
respect – el respeto
department – el departamento
access – el acceso
date – la fecha
chief – el jefe
weather – el clima
airport – el aeropuerto
machine – la máquina
window – la ventana
agenda – el orden del día
advice – el consejo
prosecution – la fiscalía
conflict – el conflicto
fall – la caída
pilot – el piloto
practice – la práctica
track – la pista
owner – el propietario
increase – el aumento
legislation – la legislación
tree – el árbol
debt – la deuda
enemy – el enemigo
truck – el camión
lead – el plomo
convention – la convención
aid – la ayuda
suicide – el suicidio
quality – la calidad
conservative – la conservadora
size – el tamaño
account – la cuenta
pleasure – el placer
institution – la institución
airline – la línea aérea
weight – el peso
approach – el enfoque
surgery – la cirugía
holiday – las vacaciones
start – el inicio
victory – la victoria
district – el distrito
relation – la relación
search – la búsqueda
crew – la tripulación
panel – el panel
coalition – la coalición
move – el movimiento
package – el paquete
check – el cheque
minority – la minoría
unit – la unidad
bag – la bolsa
surprise – la sorpresa
focus – el foco
circumstance – la circunstancia
producer – el productor
investment – la inversión
ball – la pelota
colleague – el colega
resource – el recurso
judgment – la sentencia
background – el fondo
union – la unión
address – la dirección
driver – el controlador
hero – el héroe
medicine – el medicamento
representative – el representante
vehicle – el vehículo
commander – el comandante
artist – el artista
mayor – el alcalde
run – la carrera
ship – el barco
theory – la teoría
screen – la pantalla
lesson – la lección
resident – el residente
partner – el socio
bar – el bar
ticket – el billete
disaster – el desastre
performance – el desempeño
supporter – aficionados
killer – el asesino
negotiation – la negociación
sea – el mar
wind – el viento
shoe – el zapato
secret – el secreto
tragedy – la tragedia
gift – el regalo
tour – la gira
manager – el gestor
band – la banda
birth – el nacimiento
host – el anfitrión
loan – el préstamo
allegation – la alegación
winner – el ganador
religion – la religión
article – el artículo
session – la sesión
being – el ser
extent – la medida
contract – el contrato
sentence – la sentencia
measure – la medida
deputy – el diputado
confidence – la confianza
hell – el infierno
relief – el alivio
perspective – la perspectiva
advantage – La ventaja
scandal – el escándalo
leg – la pierna
restaurant – el restaurante
dinner – la cena
client – el cliente
failure – el fracaso
quarter – el trimestre
element – el elemento
claim – la reclamación
property – la propiedad
version – la versión
attempt – el intento
bus – el autobús
customer – el cliente
appeal – la apelación
pound – la libra
protection – la protección
gene – el gen
stone – la piedra
opposition – la oposición
apartment – el apartamento
front – el frente
female – la hembra
prisoner – el prisionero
black – el negro
gang – la pandilla
principle – el principio
ally – el aliado
adviser – el asesor
visit – la visita
bird – el pájaro
stand – el soporte
communication – la comunicación
boat – el barco
connection – la conexión
key – la tecla
strike – la huelga
penalty – la pena
warning – la advertencia
luck – la suerte
dna – el ADN
spirit – el espíritu
turn – la vuelta
facility – la instalación
teenager – el adolescente
commitment – el compromiso
item – el elemento
procedure – el procedimiento de
half – la media
tank – el tanque
telephone – el teléfono
supply – el suministro
attitude – la actitud
block – el bloque
bond – el vínculo
style – el estilo
football – el fútbol
fuel – el combustible
data – los datos
glass – el cristal
suit – el traje
strength – la fuerza
criticism – las críticas
ice – el hielo
equipment – el equipo
promise – la promesa
return – el regreso
album – el álbum
production – la producción
corner – la esquina
consequence – la consecuencia
living – los vivos
injury – la lesión
cover – la tapa
spot – el punto
breast – la mama
spring – la primavera
controversy – la controversia
destruction – la destrucción
aspect – el aspecto
club – el club
aircraft – la aeronave
firm – la empresa
regime – el régimen
competition – la competencia
profit – el beneficio
knowledge – el conocimiento
spokesman – el portavoz
review – la revisión
understanding – la comprensión
recession – la recesión
singer – el cantante
village – el pueblo
arrest – la detención
snow – la nieve
joke – la broma
gold – el oro
contact – el contacto
demand – la demanda
task – la tarea
hole – el agujero
general – general
skin – la piel
count – el recuento
opponent – el oponente
conclusion – la conclusión
priority – la prioridad
rape – la violación
refugee – el refugiado
mountain – la montaña
summit – la cumbre
bottom – la parte inferior
management – la gestión
commission – la comisión
range – la gama
code – el código
cash – el dinero en efectivo
mouth – la boca
presence – la presencia
share – la cuota
fashion – la moda
shape – la forma
chair – la silla
finger – el dedo
fish – el pescado
edition – la edición
edge – el borde
limit – el límite
train – el tren
belief – la creencia
balance – el balance
exchange – el intercambio
farm – la granja
zone – la zona
passenger – el pasajero
lie – la mentira
duty – el deber
traffic – el tráfico
horse – el caballo
tradition – la tradición
recovery – la recuperación
inspector – el inspector
difficulty – la dificultad
file – el archivo
birthday – el cumpleaños
finance – la financiación
crash – el accidente
influence – la influencia
regulation – la regulación
analysis – el análisis
struggle – la lucha
heat – el calor
dress – el vestido
release – la liberación
winter – el invierno
virus – el virus
theme – el tema
notion – la noción
device – el dispositivo
anger – la ira
english – el Inglés
flag – la bandera
context – el contexto
wing – el ala
fighting – los combates
pattern – el patrón
entertainment – el entretenimiento
appearance – la aparición
saving – el ahorro
investor – el inversor
bridge – el puente
settlement – el asentamiento
rain – la lluvia
wood – la madera
mail – el correo
farmer – el agricultor
mystery – el misterio
prayer – la oración
vision – la visión
depression – la depresión
explosion – la explosión
defendant – el acusado
structure – la estructura
amendment – la enmienda
assault – el asalto
thinking – el pensamiento
therapy – la terapia
nurse – la enfermera
path – el camino
funding – la financiación
tool – la herramienta
title – el título
housing – la carcasa
shop – la tienda
complaint – la queja
wave – la ola
cat – el gato
map – el mapa
employer – el empleador
proof – la prueba
emotion – la emoción
skill – la habilidad
trust – la confianza
topic – el tema
personality – la personalidad
hall – la sala
cabinet – el armario
bone – el hueso
soul – el alma
chicken – el pollo
location – la ubicación
indication – la indicación
speaker – el altavoz
wage – el salario
era – la era
request – la solicitud
boss – el jefe
coach – el entrenador
estate – la finca
sector – el sector
egg – el huevo
stake – la estaca
stop – la parada
ring – el anillo
shock – el choque
contribution – la contribución
announcement – el anuncio
cigarette – el cigarrillo
kitchen – la cocina
territory – el territorio
command – el comando
island – la isla
protest – la protesta
impression – la impresión de
fault – el fallo
coast – la costa
reading – la lectura
variety – la variedad
revenue – los ingresos
bell – la campana
coffee – el café
alcohol – el alcohol
lunch – el almuerzo
expectation – la expectativa
grade – el grado
diet – la dieta
section – la sección
ear – el oído
sky – el cielo
assistance – la ayuda
signal – la señal
stress – el estrés
alternative – la alternativa
researcher – el investigador
cable – el cable
opening – la apertura
beach – la playa
volunteer – el voluntario
burden – la carga
detective – el detective
toy – el juguete
gain – la ganancia
asset – el activo
pool – la piscina
trend – la tendencia
survey – la encuesta
planet – el planeta
river – el río
identity – la identidad
ocean – el océano
joy – la alegría
delay – el retraso
clinic – la clínica
yard – el patio
tip – la punta
divorce – el divorcio
sun – el sol
row – la fila
phrase – la frase
worth – la pena
collection – la colección
occasion – la ocasión
surface – la superficie
tie – el empate
musician – el músico
concept – el concepto
tension – la tensión
outcome – el resultado
approval – la aprobación
fellow – el becario
beauty – la belleza
casualty – el siniestro
copy – la copia
mine – la mina
watch – el reloj
sleep – el sueño
average – la media
travel – el recorrido
fraud – el fraude
category – la categoría
exercise – el ejercicio
conviction – la convicción
initiative – la iniciativa
technique – la técnica de
recording – la grabación
sight – la vista
reduction – la reducción
whole – el conjunto
corporation – la corporación
passion – la pasión
funeral – el funeral
youth – la juventud
instrument – el instrumento
distance – la distancia
desert – el desierto
anniversary – el aniversario
writing – la escritura
invasion – la invasión
compromise – el compromiso
illness – la enfermedad
tear – el desgarro
gate – la puerta
forest – el bosque
experiment – el experimento
golf – el golf
talent – el talento
post – el cargo
gap – la brecha
priest – el sacerdote
novel – la novela
division – la división
desire – el deseo
hat – el sombrero
mortgage – la hipoteca
reputation – la reputación
score – la puntuación
shoulder – el hombro
relative – la relación
column – la columna
payment – el pago
transition – la transición
award – el premio
capability – la capacidad
definition – la definición
pocket – el bolsillo
speed – la velocidad
concert – el concierto
climate – el clima
clue – la clave
beer – La cerveza
nose – la nariz
green – el verde
garden – el jardín
satellite – el satélite
ceremony – la ceremonia
human – la humana
discovery – el descubrimiento
ride – el paseo
root – la raíz
tea – el té
motion – el movimiento
percentage – el porcentaje
combination – la combinación
explanation – la explicación
scale – la escala
chain – la cadena de
twin – el gemelo
capacity – la capacidad
dealer – el distribuidor
touch – el toque
journey – el viaje
delegate – el delegado
link – el enlace
plastic – el plástico
stimulus – el estímulo
cap – la tapa
roll – el rollo
construction – la construcción
intention – la intención
dispute – la disputa
mood – el estado de ánimo
design – el diseño
childhood – la infancia
engine – el motor
lifetime – el tiempo de vida
nightmare – la pesadilla
dance – la danza
meal – la comida
offer – la oferta
obligation – la obligación
advance – el avance
charity – la caridad
tourist – el turista
factory – la fábrica
fat – la grasa
salt – la sal de
neck – el cuello
bedroom – el dormitorio
episode – el episodio
engineer – el ingeniero
punishment – el castigo
testing – las pruebas
instance – la instancia
prospect – la perspectiva
shopping – las compras
smoke – el humo
meat – la carne
hold – la bodega
retirement – la jubilación
inflation – la inflación
`;

let wordDict = {};

let wordArray = words.split("\n");

let spanisharray = wordArray.map(word => {
  let vocab = word;

  let sparr = vocab.split(" – ");

  let spword = `${sparr[1]}`;

  let filtered = spword.split(" ");

  if (
    filtered[0] === "el" ||
    filtered[0] === "la" ||
    filtered[0] === "los" ||
    filtered[0] === "las"
  ) {
    wordDict[filtered[1]] = [];
  } else {
    wordDict[filtered[0]] = [];
  }
});

module.exports = wordDict;

let input0 = document.querySelector("#input-0");

let input1 = document.querySelector("#input-1");

let searchbar = document.querySelector("#SentenceQuery");

let searchBtn = document.querySelector(".search-submit-button");

console.dir(input0);

input1.value = "English";

input0.value = "Spanish";

//https://tatoeba.org/eng/sentences/search?from=spa&to=eng&query=congreso
//NEXT PAGE
let boxes = document.querySelectorAll(".sentence-and-translations");

let translations = Array.from(boxes);

translations.forEach(div => {
  let translation0 = div.children[0].children[1].children[1].innerText;
  let translation1 = div.children[1].children[2].children[2].innerText;
  console.log({
    sp: translation0,
    en: translation1
  });
});
